# Generated by Django 5.2.13 on 2026-04-17 13:43

import art_piece.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('painting', 'Painting'), ('architecture', 'Architecture'), ('sculpture', 'Sculpture'), ('photography', 'Photography'), ('other', 'Other')], editable=False, max_length=15)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=14, null=True, validators=[art_piece.validators.validate_year])),
                ('search_id', models.UUIDField(default=uuid.UUID('c226e999-f709-4279-aca3-f864867eaf0e'))),
                ('architect', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('painting', 'Painting'), ('architecture', 'Architecture'), ('sculpture', 'Sculpture'), ('photography', 'Photography'), ('other', 'Other')], editable=False, max_length=15)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=14, null=True, validators=[art_piece.validators.validate_year])),
                ('search_id', models.UUIDField(default=uuid.UUID('c226e999-f709-4279-aca3-f864867eaf0e'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('painting', 'Painting'), ('architecture', 'Architecture'), ('sculpture', 'Sculpture'), ('photography', 'Photography'), ('other', 'Other')], editable=False, max_length=15)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=14, null=True, validators=[art_piece.validators.validate_year])),
                ('search_id', models.UUIDField(default=uuid.UUID('c226e999-f709-4279-aca3-f864867eaf0e'))),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('technique', models.CharField(blank=True, max_length=255, null=True)),
                ('measurements', models.CharField(blank=True, max_length=255, null=True, validators=[art_piece.validators.validate_measurements])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('painting', 'Painting'), ('architecture', 'Architecture'), ('sculpture', 'Sculpture'), ('photography', 'Photography'), ('other', 'Other')], editable=False, max_length=15)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=14, null=True, validators=[art_piece.validators.validate_year])),
                ('search_id', models.UUIDField(default=uuid.UUID('c226e999-f709-4279-aca3-f864867eaf0e'))),
                ('photographer', models.CharField(blank=True, max_length=255, null=True)),
                ('camera', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sculpture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('painting', 'Painting'), ('architecture', 'Architecture'), ('sculpture', 'Sculpture'), ('photography', 'Photography'), ('other', 'Other')], editable=False, max_length=15)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=14, null=True, validators=[art_piece.validators.validate_year])),
                ('search_id', models.UUIDField(default=uuid.UUID('c226e999-f709-4279-aca3-f864867eaf0e'))),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
