# Generated by Django 5.2.13 on 2026-04-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_piece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PAINTING', 'painting'), ('ARCHITECTURE', 'architecture'), ('SCULPTURE', 'sculpture'), ('PHOTOGRAPHY', 'photography'), ('OTHER', 'other')], default='OTHER', max_length=15)),
                ('slug', models.SlugField(unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('artist', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
        migrations.AddField(
            model_name='architecture',
            name='category',
            field=models.CharField(choices=[('PAINTING', 'painting'), ('ARCHITECTURE', 'architecture'), ('SCULPTURE', 'sculpture'), ('PHOTOGRAPHY', 'photography'), ('OTHER', 'other')], default='OTHER', max_length=15),
        ),
        migrations.AddField(
            model_name='other',
            name='category',
            field=models.CharField(choices=[('PAINTING', 'painting'), ('ARCHITECTURE', 'architecture'), ('SCULPTURE', 'sculpture'), ('PHOTOGRAPHY', 'photography'), ('OTHER', 'other')], default='OTHER', max_length=15),
        ),
        migrations.AddField(
            model_name='photography',
            name='category',
            field=models.CharField(choices=[('PAINTING', 'painting'), ('ARCHITECTURE', 'architecture'), ('SCULPTURE', 'sculpture'), ('PHOTOGRAPHY', 'photography'), ('OTHER', 'other')], default='OTHER', max_length=15),
        ),
        migrations.AddField(
            model_name='sculpture',
            name='category',
            field=models.CharField(choices=[('PAINTING', 'painting'), ('ARCHITECTURE', 'architecture'), ('SCULPTURE', 'sculpture'), ('PHOTOGRAPHY', 'photography'), ('OTHER', 'other')], default='OTHER', max_length=15),
        ),
    ]
