# Generated by Django 5.2.13 on 2026-04-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_piece', '0002_painting_delete_artwork_architecture_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('architecture', 'Architecture'), ('sculpture', 'Sculpture'), ('photography', 'Photography'), ('other', 'Other')], editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='other',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('architecture', 'Architecture'), ('sculpture', 'Sculpture'), ('photography', 'Photography'), ('other', 'Other')], editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='painting',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('architecture', 'Architecture'), ('sculpture', 'Sculpture'), ('photography', 'Photography'), ('other', 'Other')], editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='photography',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('architecture', 'Architecture'), ('sculpture', 'Sculpture'), ('photography', 'Photography'), ('other', 'Other')], editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('architecture', 'Architecture'), ('sculpture', 'Sculpture'), ('photography', 'Photography'), ('other', 'Other')], editable=False, max_length=15),
        ),
    ]
