# Generated by Django 5.2.13 on 2026-04-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_piece', '0003_alter_architecture_category_alter_other_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architecture',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='other',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='painting',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='photography',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sculpture',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
