# Generated by Django 5.2.13 on 2026-04-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_piece', '0004_rename_created_date_architecture_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='architect',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photography',
            name='photographer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
