# Generated by Django 5.2.13 on 2026-04-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_piece', '0006_architecture_location_architecture_year_built_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='architecture',
            old_name='year_built',
            new_name='year',
        ),
        migrations.AddField(
            model_name='other',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
