# Generated by Django 5.2.13 on 2026-04-15 11:18

import art_piece.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_piece', '0008_alter_architecture_year_alter_other_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='year',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[art_piece.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='other',
            name='year',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[art_piece.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='painting',
            name='year',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[art_piece.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='photography',
            name='year',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[art_piece.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='sculpture',
            name='year',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[art_piece.validators.validate_year]),
        ),
    ]
