# Generated by Django 5.2.13 on 2026-04-17 12:08

import art_piece.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_piece', '0009_alter_architecture_year_alter_other_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='measurements',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[art_piece.validators.validate_measurements]),
        ),
    ]
